// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKXKQQCSldMUsKtKv5YL4qbwMokl2klnU',
    appId: '1:489290585479:web:9558479217b0ebf2b7ef22',
    messagingSenderId: '489290585479',
    projectId: 'daylyse',
    authDomain: 'daylyse.firebaseapp.com',
    storageBucket: 'daylyse.appspot.com',
    measurementId: 'G-60X5FR1E2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp06GqV9cxGwE36BTFK--Y-OZG6bY4NS8',
    appId: '1:489290585479:android:6f89c0be05ed2a58b7ef22',
    messagingSenderId: '489290585479',
    projectId: 'daylyse',
    storageBucket: 'daylyse.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBca07mXI3NYPaHL8U0IuZlKxm6_nrlS10',
    appId: '1:489290585479:ios:99e16fd131bf82dfb7ef22',
    messagingSenderId: '489290585479',
    projectId: 'daylyse',
    storageBucket: 'daylyse.appspot.com',
    iosBundleId: 'com.example.daylyse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBca07mXI3NYPaHL8U0IuZlKxm6_nrlS10',
    appId: '1:489290585479:ios:99e16fd131bf82dfb7ef22',
    messagingSenderId: '489290585479',
    projectId: 'daylyse',
    storageBucket: 'daylyse.appspot.com',
    iosBundleId: 'com.example.daylyse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKXKQQCSldMUsKtKv5YL4qbwMokl2klnU',
    appId: '1:489290585479:web:d64c6ad8266cecb1b7ef22',
    messagingSenderId: '489290585479',
    projectId: 'daylyse',
    authDomain: 'daylyse.firebaseapp.com',
    storageBucket: 'daylyse.appspot.com',
    measurementId: 'G-MBL2VQ8L9H',
  );
}
